name: container

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.05-small

      - name: Flake checks
        run: nix flake check -L --no-write-lock-file

      - name: Build image tarball
        run: nix build -L --no-write-lock-file .#homebase


      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: nix run .#homebase.copyToRegistry --no-sandbox
